### ISSUE TITLE
Need for a view on the top of pg_stat_monitor to produce similar results as pg_stat_statements

### ISSUE THREAD

**Issue by dutow** [percona/pg_stat_monitor#416] opened 2023-07-17 08:20 UTC
In Support, We are dealing with customers who have pg_stat_statement (a large portion) and those who are going to have pg_stat_monitor.
All our analysis queries and scripts are targeted for pg_stat_statement. So a view that provides similar output as pg_stat_statement is important when we deal with unknown customer environments.

https://jira.percona.com/browse/PG-334

**Comment by ImTheKai** [comment] 2024-07-10 08:00
Duplicate of https://github.com/percona/pg_stat_monitor/issues/431

**Closed by ImTheKai** 2024-07-10 08:00 UTC
